##
## list of functions
##
# in.simplex
# simplex
# tab1.hgm
# tab1.mc
# tab1.src
# tab1

##
## Evaluate simplex probability by Monte Carlo method.
##
in.simplex <- function(x){
 d <- length(x)
 b <- 0.5*sqrt(d)
 IN <- TRUE
 for( i in 1:d){
  if( x[i] + b < 0.0) IN <- FALSE
 }
 if(-sum(x)+b < 0.0) 
  IN <- FALSE
 return(IN)
}

simplex <- function(dd, N){
 result <- rep(0, length(dd))
 for( ii in 1:length(dd)){
   d <- dd[ii]
   x <- matrix(rnorm(N*d),nrow=d)
   v <- apply(x, 2, in.simplex)
   s <- length(v[v==TRUE])
   result[ii] <- s/N
 }
 return(result) 
}

##
## Evaluate simplicial cone probability by Monte Carlo method.
##
in.simplicial_cone <- function(x){
 d <- length(x)
 a <- matrix(rep(0,d*d), nrow = d)
 for( i in 1:d) a[i,i] <- 1.0
 for( i in 1:(d-1)){
  for( j in (i+1):d){
   a[i,j] <- 0.01 * (i+j);
  }
 }
 b <- 0.5 * sqrt(d) * rep(1,d) #sqrt(d) * seq(1,d)
# print(a)
# print(b)
 IN <- TRUE
 for( i in 1:d){
  if( a[,i] %*% x + b[i] < 0.0) IN <- FALSE
 }
 return(IN)
}

simplicial_cone <- function(dd, N){
 result <- rep(0, length(dd))
 for( ii in 1:length(dd)){
   d <- dd[ii]
   x <- matrix(rnorm(N*d),nrow=d)
   v <- apply(x, 2, in.simplicial_cone)
   s <- length(v[v==TRUE])
   result[ii] <- s/N
 }
 return(result) 
}

##
## Evaluate simplex probability by Monte Carlo method(small case).
##
in.simplex_s <- function(x){
 d <- length(x)
 b <- 0.5*sqrt(d)
 IN <- TRUE
 for( i in 1:d){
  if( x[i] - b < 0.0) IN <- FALSE
 }
 if(-sum(x)+(d+0.5)*sqrt(d) < 0.0) 
  IN <- FALSE
 return(IN)
}

simplex_s <- function(dd, N){
 result <- rep(0, length(dd))
 for( ii in 1:length(dd)){
   d <- dd[ii]
   x <- matrix(rnorm(N*d),nrow=d)
   v <- apply(x, 2, in.simplex_s)
   s <- length(v[v==TRUE])
   result[ii] <- s/N
 }
 return(result) 
}

##
## functions for tab1.  
##
tab1.hgm <- function(Dim,N){
  l  <- readLines("raw_data1.txt")
  dl <- l[grep("dim", l)]
  pl <- l[grep("probability", l)]
  tl <- l[grep("User",l)]
  d  <- as.numeric(gsub("dim=","",dl))
  p  <- as.numeric(gsub("probability= ","",pl))
  t  <- as.numeric(substr(tl, 23, 26))
  data.frame(d=d,p=p,t=t)
}
 
tab1.mc <- function(Dim,N){
  d <- c(2:Dim)
  p <- simplex(d,N)
  data.frame(d=d,p=p)
}

tab1.src <- function(h,m){
  t <- c("%% tab1 was generated by monte_carlo.R\n");
  t <- append(t,"\\begin{table}[htbp]\n" );
  t <- append(t,"\\begin{center}\n" );
  t <- append(t,"\\begin{tabular}{cccc}\n" );
  t <- append(t,"dim& HGM & time of HGM(s) & MC\\\\\n" );
  t <- append(t,"\\hline\n" );

  t <- append(t,sprintf("%d & %8.6f & %3.2f & %8.6f\\\\\n",h$d, h$p, h$t, m$p) );

  t <- append(t,"\\hline\n");
  t <- append(t,"\\end{tabular}\n");
  t <- append(t,"\\end{center}\n");
  t <- append(t,"\\caption{Results of HGM for simplex probabilities}\n");
  t <- append(t,"\\label{tab1}\n");
  t <- append(t,"\\end{table}\n");
  t <- append(t,"");

  return(t)
}

tab1 <- function(Dim, N){
 hgm <- tab1.hgm(Dim,N)
 mc  <- tab1.mc(Dim,N)
 src <- tab1.src(hgm, mc)

 print(src)

 sink("tab1.tex")
 for( i in 1:length(src)){
   cat(src[i])
 }
 sink()
}

##
## functions for tab2.  
##
tab2.hgm <- function(Dim,N){
  l  <- readLines("raw_data2.txt")
  dl <- l[grep("dim", l)]
  pl <- l[grep("probability", l)]
  tl <- l[grep("User",l)]
  d  <- as.numeric(gsub("dim=","",dl))
  p  <- as.numeric(gsub("probability= ","",pl))
  t  <- as.numeric(substr(tl, 23, 26))
  data.frame(d=d,p=p,t=t)
}
 
tab2.mc <- function(Dim,N){
  d <- c(2:Dim)
  p <- simplicial_cone(d,N)
  data.frame(d=d,p=p)
}

tab2.src <- function(h,m){
  t <- c("%% tab2 was generated by monte_carlo.R\n");
  t <- append(t,"\\begin{table}[htbp]\n" );
  t <- append(t,"\\begin{center}\n" );
  t <- append(t,"\\begin{tabular}{cccc}\n" );
  t <- append(t,"dim& HGM & time of HGM(s) & MC\\\\\n" );
  t <- append(t,"\\hline\n" );

  t <- append(t,sprintf("%d & %8.6f & %3.2f & %8.6f\\\\\n",h$d, h$p, h$t, m$p) );

  t <- append(t,"\\hline\n");
  t <- append(t,"\\end{tabular}\n");
  t <- append(t,"\\end{center}\n");
  t <- append(t,"\\caption{Results of HGM for normal probabilities of simplicial cones}\n");
  t <- append(t,"\\label{tab2}\n");
  t <- append(t,"\\end{table}\n");
  t <- append(t,"");

  return(t)
}

tab2 <- function(Dim, N){
 hgm <- tab2.hgm(Dim,N)
 mc  <- tab2.mc(Dim,N)
 src <- tab2.src(hgm, mc)

 print(src)

 sink("tab2.tex")
 for( i in 1:length(src)){
   cat(src[i])
 }
 sink()
}

##
## functions for tab3.  
##
tab3.hgm <- function(Dim,N){
  l  <- readLines("raw_data3.txt")
  dl <- l[grep("dim", l)]
  pl <- l[grep("probability", l)]
  tl <- l[grep("User",l)]
  d  <- as.numeric(gsub("dim=","",dl))
  p  <- as.numeric(gsub("probability= ","",pl))
  t  <- as.numeric(substr(tl, 23, 26))
  data.frame(d=d,p=p,t=t)
}
 
tab3.mc <- function(Dim,N){
  d <- c(2:Dim)
  p <- simplex_s(d,N)
  data.frame(d=d,p=p)
}

tab3.src <- function(h,m){
  t <- c("%% tab3 was generated by monte_carlo.R\n");
  t <- append(t,"\\begin{table}[htbp]\n" );
  t <- append(t,"\\begin{center}\n" );
  t <- append(t,"\\begin{tabular}{cccc}\n" );
  t <- append(t,"dim& HGM & time of HGM(s) & MC\\\\\n" );
  t <- append(t,"\\hline\n" );

  t <- append(t,sprintf("%d & %5.4e & %3.2f & %5.4e\\\\\n",h$d, h$p, h$t, m$p) );

  t <- append(t,"\\hline\n");
  t <- append(t,"\\end{tabular}\n");
  t <- append(t,"\\end{center}\n");
  t <- append(t,"\\caption{Results of HGM for simplex probabilities(Small case)}\n");
  t <- append(t,"\\label{tab3}\n");
  t <- append(t,"\\end{table}\n");
  t <- append(t,"");

  return(t)
}

tab3 <- function(Dim, N){
 hgm <- tab3.hgm(Dim,N)
 mc  <- tab3.mc(Dim,N)
 src <- tab3.src(hgm, mc)

 #print(hgm)
 #print(mc)
 print(src)

 sink("tab3.tex")
 for( i in 1:length(src)){
   cat(src[i])
 }
 sink()
}

##
## main
##
set.seed(101)

MAXDIM <- 10
NSAMPLES <- 1e+06

tab1(MAXDIM,NSAMPLES)
tab2(MAXDIM,NSAMPLES)
tab3(MAXDIM,NSAMPLES)